-- Disable triggers and clear tables in order of dependency
TRUNCATE 
  public.event_deployments,
  public.notifications,
  public.report_rows,
  public.reports,
  public.agriculture_damage_reports,
  public.assistance_lgus_agencies_reports,
  public.assistance_provided_reports,
  public.class_suspension_reports,
  public.communication_lines_reports,
  public.damaged_houses_reports,
  public.declaration_state_of_calamity_reports,
  public.infrastructure_damage_reports,
  public.power_reports,
  public.pre_emptive_evacuation_reports,
  public.related_incidents,
  public.roads_and_bridges_sections,
  public.roads_and_bridges,
  public.water_supply_reports,
  public.work_suspension_reports,
  public.situational_reports,
  public.events,
  public.activity_logs
RESTART IDENTITY CASCADE;
