-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  action text NOT NULL,
  details text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.agriculture_damage_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  situational_report_id uuid,
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  classification text DEFAULT ''::text,
  type text DEFAULT ''::text,
  farmers_affected integer DEFAULT 0,
  area_totally_damaged numeric DEFAULT 0,
  area_partially_damaged numeric DEFAULT 0,
  area_total numeric DEFAULT 0,
  infra_totally_damaged numeric DEFAULT 0,
  infra_partially_damaged numeric DEFAULT 0,
  infra_total numeric DEFAULT 0,
  production_loss_volume numeric DEFAULT 0,
  production_loss_value numeric DEFAULT 0,
  status text DEFAULT 'Ongoing'::text,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  CONSTRAINT agriculture_damage_reports_pkey PRIMARY KEY (id),
  CONSTRAINT agriculture_damage_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT agriculture_damage_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.assistance_lgus_agencies_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  situational_report_id uuid,
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  type text DEFAULT ''::text,
  qty numeric DEFAULT 0,
  unit text DEFAULT ''::text,
  cost_per_unit numeric DEFAULT 0,
  amount numeric DEFAULT 0,
  source text DEFAULT ''::text,
  remarks text DEFAULT ''::text,
  status text DEFAULT 'Ongoing'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  CONSTRAINT assistance_lgus_agencies_reports_pkey PRIMARY KEY (id),
  CONSTRAINT assistance_lgus_agencies_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT assistance_lgus_agencies_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.assistance_provided_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  no_families_affected integer,
  needs text DEFAULT ''::text,
  no_families_requiring_assistance integer,
  fnfi_qty numeric,
  fnfi_unit text DEFAULT ''::text,
  fnfi_cost_per_unit numeric,
  fnfi_amount numeric,
  fnfi_source text DEFAULT ''::text,
  no_families_assisted integer,
  pct_families_assisted numeric,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Ongoing'::text,
  city text DEFAULT ''::text,
  CONSTRAINT assistance_provided_reports_pkey PRIMARY KEY (id),
  CONSTRAINT assistance_provided_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT assistance_provided_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.class_suspension_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  level_from text DEFAULT ''::text,
  level_to text DEFAULT ''::text,
  type text DEFAULT ''::text,
  date_of_suspension date,
  time_of_suspension time without time zone,
  date_resumed date,
  time_resumed time without time zone,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Ongoing'::text,
  CONSTRAINT class_suspension_reports_pkey PRIMARY KEY (id),
  CONSTRAINT class_suspension_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT class_suspension_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.communication_lines_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  telecompany text DEFAULT ''::text,
  status_of_communication text DEFAULT ''::text,
  date_interruption date,
  time_interruption time without time zone,
  date_restoration date,
  time_restoration time without time zone,
  site_count_2g integer,
  with_coverage_2g integer,
  pct_coverage_2g numeric,
  site_count_3g integer,
  with_coverage_3g integer,
  pct_coverage_3g numeric,
  site_count_4g integer,
  with_coverage_4g integer,
  pct_coverage_4g numeric,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Operational'::text,
  CONSTRAINT communication_lines_reports_pkey PRIMARY KEY (id),
  CONSTRAINT communication_lines_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT communication_lines_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.damaged_houses_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  totally_damaged integer DEFAULT 0,
  partially_damaged integer DEFAULT 0,
  grand_total integer DEFAULT 0,
  amount_php numeric,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Reported'::text,
  CONSTRAINT damaged_houses_reports_pkey PRIMARY KEY (id),
  CONSTRAINT damaged_houses_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT damaged_houses_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.declaration_state_of_calamity_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  type text DEFAULT ''::text,
  count_soc integer,
  resolution_number text DEFAULT ''::text,
  resolution_date date,
  remarks text DEFAULT ''::text,
  attachment_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Declared'::text,
  CONSTRAINT declaration_state_of_calamity_reports_pkey PRIMARY KEY (id),
  CONSTRAINT declaration_state_of_calamity_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT declaration_state_of_calamity_report_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  event_type text,
  alert_status text,
  color text,
  created_at timestamp with time zone DEFAULT now(),
  summary text,
  approval_status text DEFAULT 'Pending'::text,
  approved_pdf_url text,
  pinged_report_types jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.infrastructure_damage_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  situational_report_id uuid,
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  type text DEFAULT ''::text,
  classification text DEFAULT ''::text,
  infrastructure_name text DEFAULT ''::text,
  number_damaged integer DEFAULT 0,
  unit text DEFAULT ''::text,
  quantity numeric DEFAULT 0,
  cost numeric DEFAULT 0,
  status text DEFAULT 'Ongoing'::text,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  CONSTRAINT infrastructure_damage_reports_pkey PRIMARY KEY (id),
  CONSTRAINT infrastructure_damage_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT infrastructure_damage_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.power_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  type text NOT NULL,
  service_provider text NOT NULL,
  date_of_interruption date NOT NULL,
  time_of_interruption time without time zone,
  date_restored date,
  time_restored time without time zone,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Ongoing'::text,
  CONSTRAINT power_reports_pkey PRIMARY KEY (id),
  CONSTRAINT power_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT power_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.pre_emptive_evacuation_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  families integer,
  male_count integer,
  female_count integer,
  total integer,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Completed'::text,
  CONSTRAINT pre_emptive_evacuation_reports_pkey PRIMARY KEY (id),
  CONSTRAINT pre_emptive_evacuation_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT pre_emptive_evacuation_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.related_incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  type_of_incident text NOT NULL,
  date_of_occurrence date NOT NULL,
  time_of_occurrence time without time zone,
  description text DEFAULT ''::text,
  actions_taken text DEFAULT ''::text,
  remarks text DEFAULT ''::text,
  status text DEFAULT 'Ongoing'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  CONSTRAINT related_incidents_pkey PRIMARY KEY (id),
  CONSTRAINT related_incidents_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT related_incidents_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.report_rows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  barangay text NOT NULL,
  affected_families integer DEFAULT 0,
  affected_persons integer DEFAULT 0,
  ecs_cum integer DEFAULT 0,
  ecs_now integer DEFAULT 0,
  inside_families_cum integer DEFAULT 0,
  inside_families_now integer DEFAULT 0,
  inside_persons_cum integer DEFAULT 0,
  inside_persons_now integer DEFAULT 0,
  outside_families_cum integer DEFAULT 0,
  outside_families_now integer DEFAULT 0,
  outside_persons_cum integer DEFAULT 0,
  outside_persons_now integer DEFAULT 0,
  status text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_rows_pkey PRIMARY KEY (id),
  CONSTRAINT report_rows_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.roads_and_bridges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  classification text NOT NULL DEFAULT 'Other'::text,
  status text DEFAULT ''::text,
  date_reported_passable date,
  time_reported_passable time without time zone,
  date_reported_not_passable date,
  time_reported_not_passable time without time zone,
  event_id uuid,
  situational_report_id uuid,
  type text DEFAULT 'Road'::text,
  CONSTRAINT roads_and_bridges_pkey PRIMARY KEY (id),
  CONSTRAINT roads_and_bridges_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT roads_and_bridges_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.roads_and_bridges_sections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roads_and_bridges_sections_pkey PRIMARY KEY (id),
  CONSTRAINT roads_and_bridges_sections_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.roads_and_bridges(id)
);
CREATE TABLE public.signatories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  position text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signatories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.situational_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid,
  report_number integer NOT NULL,
  title text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  status text DEFAULT 'Draft'::text,
  CONSTRAINT situational_reports_pkey PRIMARY KEY (id),
  CONSTRAINT situational_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text DEFAULT ''::text,
  city text DEFAULT ''::text,
  role text DEFAULT 'Viewer'::text,
  status text DEFAULT 'Active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  password_hash text,
  account_type text,
  province text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.water_supply_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  service_provider text NOT NULL,
  date_of_interruption date NOT NULL,
  time_of_interruption time without time zone,
  date_restored date,
  time_restored time without time zone,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  status text DEFAULT 'Ongoing'::text,
  situational_report_id uuid,
  barangay text,
  city text DEFAULT ''::text,
  CONSTRAINT water_supply_reports_pkey PRIMARY KEY (id),
  CONSTRAINT water_supply_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT water_supply_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);
CREATE TABLE public.work_suspension_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barangay text NOT NULL,
  city text DEFAULT ''::text,
  type text DEFAULT ''::text,
  date_of_suspension date,
  time_of_suspension time without time zone,
  date_resumed date,
  time_resumed time without time zone,
  remarks text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  event_id uuid,
  situational_report_id uuid,
  status text DEFAULT 'Ongoing'::text,
  CONSTRAINT work_suspension_reports_pkey PRIMARY KEY (id),
  CONSTRAINT work_suspension_reports_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT work_suspension_reports_situational_report_id_fkey FOREIGN KEY (situational_report_id) REFERENCES public.situational_reports(id)
);